# Generated by Django 4.1.7 on 2023-02-22 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('count_views', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='ViewMyPage',
        ),
    ]
