# Generated by Django 4.1.7 on 2023-02-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_views', '0002_rename_view_viewmypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmypage',
            name='city',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='country',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='country_name',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='ip',
            field=models.CharField(default='NONE', max_length=40),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='page',
            field=models.CharField(default='NONE', max_length=10),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='region',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='user',
            field=models.CharField(default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='viewmypage',
            name='version',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
