# Generated by Django 4.1.7 on 2023-03-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count_views', '0003_viewmypage_city_viewmypage_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewmypage',
            name='country_name_iso_2',
            field=models.CharField(default='NON', max_length=3),
        ),
    ]
